"""Add project_collaborators and project_assignments

Revision ID: 878133c46a88
Revises: 2d277c9a871a
Create Date: 2025-02-15 17:36:24.366093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '878133c46a88'
down_revision: Union[str, None] = '2d277c9a871a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'projects', 'templates', ['template_id'], ['id'])
    op.drop_column('projects', 'assignments')
    op.drop_column('projects', 'collaborators')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('collaborators', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('assignments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    # ### end Alembic commands ###
